trucks_data = [
  {'make': 'Scania', 'model': 'G500', 'year': '2024', 'type': 'V8 Puller', 'engine': 'Inline', 'power': '500 HP@1900 rpm', 'torque': '2550 Nm@1000-1300 rpm', 'fuel_system': 'Diesel', 'fuel_control': 'NA', 'ignition': 'TCBI with digital advance', 'lubrication': 'Forced lubrication, wet sump', 'cooling': 'Liquid', 'gearbox': '6-speed', 'transmission': '14 Speed', 'clutch': 'Single dry plate clutch', 'front_suspension': 'no data', 'rear_suspension': 'no data', 'front_brakes': 'no data', 'rear_brakes': 'no data', 'main_brake': 'no data', 'additional_brake': 'no data', 'fuel_capacity': '500 Litres', 'electricals_batery': '2x12 V, 180 Ah', 'price': '6,507.56'},

{'make': 'Ashok', 'model': 'Leyland', 'year': '2023', 'type': '2518', 'engine': 'H Series 5.7L CRS TCIC - iEGR Technology', 'power': '250 HP@2300 rpm', 'torque': '950 Nm@1000-1800 rpm', 'fuel_system': 'Common Rail', 'fuel_control': 'Diesel', 'gearbox': 'ALGB940', 'transmission': '6 speed (6F+1R)', 'clutch': '380 mm dia, With clutch booster', 'front_suspension': 'no data', 'rear_suspension': 'no data', 'front_brakes': 'no data', 'rear_brakes': 'no data', 'main_brake': 'no data', 'additional_brake': 'no data', 'fuel_capacity': '400 Litres', 'electricals_batery': '24V, 110 Ah', 'price': '30,332.84'},

{'make': 'Chevrolet', 'model': 'Silverado 1500', 'year': '2025', 'type': 'Regular Cab Standar', 'engine': 'Turbocharged Gas I4', 'power': '310 @ 5600', 'torque': '430 @ 3000', 'fuel_system': 'Direct Injection', 'fuel_control': 'no data', 'gearbox': '10-speed', 'transmission': 'Automatic', 'clutch': 'Double-plate clutch with 400 mm diameter', 'front_suspension': 'Independent coil-over-shock', 'rear_suspension': 'Solid Axle', 'front_brakes': 'no data', 'rear_brakes': 'no data', 'main_brake': 'no data', 'additional_brake': 'no data', 'fuel_capacity': '2.4L/166', 'electricals_batery': 'Electric Rack & Pinion', 'price': '33,918.00'},

{'make': 'Tata', 'model': 'LPT', 'year': '2022', 'type': '4225', 'engine': 'Cummins ISBe 6.7L', 'power': '250 HP@2300 rpm', 'torque': '950 Nm@1000-1800 rpm', 'fuel_system': 'Common Rail', 'fuel_control': 'Diesel', 'ignition': 'TCBI with digital advance', 'lubrication': 'Forced lubrication, wet sump', 'cooling': 'Liquid', 'gearbox': 'G950', 'transmission': '6 speed (6F+1R)', 'clutch': '395 mm dia, Organic', 'front_suspension': 'no data', 'rear_suspension': 'no data', 'front_brakes': 'no data', 'rear_brakes': 'no data', 'main_brake': 'no data', 'additional_brake': 'no data', 'fuel_capacity': '365 / 300 Litres - Polymer tank', 'electricals_batery': 'NA', 'price': '5,756.68'},

{'make': 'Mercedes-Benz', 'model': 'Actros 2645 LS', 'year': '2023', 'type': 'OM 501 LA', 'engine': 'Unit Pump System (UPS)', 'torque': 'Max. power (HP/rpm) 394/1800 - 1850/1080', 'fuel_system': 'no data', 'fuel_control': 'no data', 'gearbox': 'no data', 'transmission': 'Manual Transmission with Telligent Gearshift', 'clutch': 'Double-plate clutch with 400 mm diameter', 'front_suspension': '7.1 t, parabolic springs', 'rear_suspension': '2 x 9.5 t, 4-bags air suspension', 'front_brakes': '7.5 t, offset. ', 'rear_brakes': 'no data', 'main_brake': 'Drum  brakes on front and rear axle, Dual-circuit full air brakes, automatic brake adjusting, roll-back prevention, Telligent braking system with ABS and ASR, independent trailer brakes 2-lines', 'additional_brake': 'Air actuated engine brake with compression valve', 'fuel_capacity': '400 ltr. Steel', 'starter': 'Electric', 'price': '47,168.55'},

{'make': 'Volvo', 'model': 'FM 420', 'year': '2023', 'type': 'LNG', 'engine': 'In-line direct-injection engine', 'power': '420 HP', 'torque': '2100 Nm', 'fuel_system': 'Direct Injection', 'fuel_control': 'Liquefied Natural Gas (LNG)', 'gearbox': '12F-4R', 'transmission': '12 Speed 1000 Km range (approx)', 'clutch': 'Power assisted & Push-type single plate friction disc', 'front_suspension': 'no data', 'rear_suspension': 'no data', 'rear_brakes': 'no data', 'main_brake': 'no data', 'additional_brake': 'no data', 'fuel_capacity': 'no data', 'electricals_batery': '2x12 V, 170 Ah', 'price': '37,645'}
]

# for truck in trucks_data:
#   print(f"{truck['make']} {truck['model']} {truck['type']}")